version: '3'
services:
  myapp:
    container_name: himaapp-react-native
    tty: true
    build:
      context: ./HimaApp
      dockerfile: ./Dockerfile
    volumes:
      # - /myapp/node_modules
      - ./HimaApp:/HimaApp
    env_file: ./HimaApp/.env
    ports:
      - 8081:8081
