version: '3'
services:
  myapp:
    container_name: myapp-react-native
    tty: true
    build:
      context: ./myapp
      dockerfile: ./Dockerfile
    volumes:
      # - /myapp/node_modules
      - ./myapp:/myapp
    env_file: ./myapp/.env
    ports:
      - 8081:8081
